# Generated by Django 2.1.7 on 2019-04-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('for_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.College', verbose_name='Question For College')),
                ('for_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Department', verbose_name='Question For Department')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='Reply')),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question', verbose_name='Question')),
            ],
        ),
    ]
