# Generated by Django 2.1.7 on 2019-04-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_school', models.CharField(max_length=150, verbose_name='10th School')),
                ('metric_board', models.CharField(max_length=50, verbose_name='10th Board')),
                ('metric_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='10th Percentage')),
                ('metric_pass_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=student.models.AcademicQualification.current_year, verbose_name='10th Passing Year')),
                ('inter_school', models.CharField(max_length=150, verbose_name='12th School/College')),
                ('inter_board', models.CharField(max_length=50, verbose_name='12th Board')),
                ('inter_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='12th Percentage')),
                ('inter_pass_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=student.models.AcademicQualification.current_year, verbose_name='12th Passing Year')),
                ('graduation_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Graduation Percentage')),
            ],
            options={
                'verbose_name_plural': '02. Academic Qualifications',
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=50, verbose_name='Hobby')),
            ],
            options={
                'verbose_name_plural': '06. Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Company')),
                ('duration', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Internship Duration (months)')),
                ('internship_on', models.CharField(max_length=50, verbose_name='Internship On')),
            ],
            options={
                'verbose_name_plural': '08. Internships',
            },
        ),
        migrations.CreateModel(
            name='LanguagesKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bhojpuri', 'Bhojpuri')], max_length=12, verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': '07. Languages Known',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_objective', models.TextField(default='To secure a responsible career opportunity to full utilize my knowledge, training and skills, while making a significant contribution to the success of the company/organization. ', verbose_name='Career Objective')),
                ('fb_link', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(blank=True, verbose_name='Twitter Link')),
                ('insta_link', models.URLField(blank=True, verbose_name='Instragram Link')),
                ('github_link', models.URLField(blank=True, verbose_name='Github Link')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': '01. Portfolios',
            },
        ),
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_summary', to='student.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': '05. Profile Summary',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Academic Project', 'Academic Project'), ('Non Academic Project', 'Non Academic Project')], max_length=50, verbose_name='Project Type')),
                ('title', models.CharField(max_length=250, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('github_link', models.URLField(blank=True, verbose_name='Project Github Link')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': '09. Projects',
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=250, verbose_name='Skill')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='student.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': '03. Skill Set',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Database', 'Database'), ('Operating Systems', 'Operating System'), ('Web Development (Frontend)', 'Web Development (Frontend)'), ('Web Development (Backend)', 'Web Development (Backend)'), ('Other', 'Other')], max_length=100, verbose_name='Title')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
                ('skill_level', models.IntegerField(verbose_name='Skill Level')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skill', to='student.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': '04. Technical Skills',
            },
        ),
        migrations.CreateModel(
            name='TechnologyUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_used', to='student.Project', verbose_name='Project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TechnicalSkill', verbose_name='Technology Used')),
            ],
            options={
                'verbose_name_plural': '10. Technology Used (in project)',
            },
        ),
        migrations.AddField(
            model_name='languagesknown',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_known', to='student.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='internship',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='student.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='student.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='academicqualification',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualification', to='student.Portfolio', verbose_name='Portfolio'),
        ),
    ]
