# Generated by Django 2.1.7 on 2019-04-04 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_school', models.CharField(max_length=150, verbose_name='10th School')),
                ('metric_board', models.CharField(max_length=50, verbose_name='10th Board')),
                ('metric_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='10th Percentage')),
                ('metric_pass_year', models.DateField(verbose_name='10th Passing Year')),
                ('inter_school', models.CharField(max_length=150, verbose_name='12th School/College')),
                ('inter_board', models.CharField(max_length=50, verbose_name='12th Board')),
                ('inter_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='12th Percentage')),
                ('inter_pass_year', models.DateField(verbose_name='12th Passing Year')),
                ('graduation_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Graduation Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=50, verbose_name='Hobby')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Company')),
                ('duration', models.DurationField(verbose_name='Internship Duration')),
                ('internship_on', models.CharField(max_length=50, verbose_name='Internship On')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50, verbose_name="Farther's Name")),
                ('career_objective', models.TextField(default='To secure a responsible career opportunity to full utilize my knowledge, training and skills, while making a significant contribution to the success of the company/organization. ', verbose_name='Career Objective')),
                ('fb_link', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(blank=True, verbose_name='Twitter Link')),
                ('insta_link', models.URLField(blank=True, verbose_name='Instragram Link')),
                ('github_link', models.URLField(blank=True, verbose_name='Github Link')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_summary', to='student.Portfolio', verbose_name='Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Academic Project', 'Academic Project'), ('Non Academic Project', 'Non Academic Project')], max_length=50, verbose_name='Project Type')),
                ('title', models.CharField(max_length=250, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('github_link', models.URLField(blank=True, verbose_name='Project Github Link')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.Portfolio', verbose_name='Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=250, verbose_name='Skill')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='student.Portfolio', verbose_name='Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Database', 'Database'), ('Operating Systems', 'Operating System'), ('Web Development (Frontend)', 'Web Development (Frontend)'), ('Web Development (Backend)', 'Web Development (Backend)'), ('Other', 'Other')], max_length=100, verbose_name='Title')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
                ('skill_level', models.IntegerField(verbose_name='Skill Level')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skill', to='student.Portfolio', verbose_name='Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_used', to='student.Project', verbose_name='Project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TechnicalSkill', verbose_name='Technology Used')),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='student.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='academicqualification',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualification', to='student.Portfolio', verbose_name='Portfolio'),
        ),
    ]
