# Generated by Django 2.1.7 on 2019-04-21 16:43

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='graduation_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='inter_board',
            field=models.CharField(max_length=50, null=True, verbose_name='12th Board'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='inter_pass_year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=student.models.AcademicQualification.current_year, null=True, verbose_name='12th Passing Year'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='inter_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='12th Percentage'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='inter_school',
            field=models.CharField(max_length=150, null=True, verbose_name='12th School/College'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='metric_board',
            field=models.CharField(max_length=50, null=True, verbose_name='10th Board'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='metric_pass_year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=student.models.AcademicQualification.current_year, null=True, verbose_name='10th Passing Year'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='metric_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='10th Percentage'),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='metric_school',
            field=models.CharField(max_length=150, null=True, verbose_name='10th School'),
        ),
    ]
