# Generated by Django 2.1.7 on 2019-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190405_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Internship Duration (months)'),
        ),
    ]
