# Generated by Django 2.1.7 on 2019-04-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190405_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicqualification',
            options={'verbose_name_plural': '2. Academic Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': '6. Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'verbose_name_plural': '7. Internships'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': '1. Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='profilesummary',
            options={'verbose_name_plural': '5. Profile Summary'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '8. Projects'},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'verbose_name_plural': '3. Skill Set'},
        ),
        migrations.AlterModelOptions(
            name='technicalskill',
            options={'verbose_name_plural': '4. Technical Skills'},
        ),
        migrations.AlterModelOptions(
            name='technologyused',
            options={'verbose_name_plural': '9. Technology Used (in project)'},
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualification', to='student.Portfolio', verbose_name='Portfolio'),
        ),
    ]
