# Generated by Django 2.1.7 on 2019-04-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190405_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bhojpuri', 'Bhojpuri')], max_length=12, verbose_name='Language')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': '7. Languages Known',
            },
        ),
    ]
