# Generated by Django 2.1.7 on 2019-04-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Farther's Name"),
        ),
    ]
