# Generated by Django 2.1.5 on 2019-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190308_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(upload_to='admin/profile_pics/'),
        ),
    ]
