# Generated by Django 2.1.7 on 2019-04-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_father_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': '1. Colleges'},
        ),
        migrations.AlterModelOptions(
            name='collegenotice',
            options={'verbose_name_plural': '5. College Notice Board'},
        ),
        migrations.AlterModelOptions(
            name='collegepictures',
            options={'verbose_name_plural': '4. College Pictures'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '3. Unital Notice'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '2. Users'},
        ),
    ]
