# Generated by Django 2.1.5 on 2019-03-08 17:48

from django.db import migrations, models
import django.utils.timezone
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190308_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expire_date',
            field=models.DateField(default=main_app.models.Notice.thirty_day_hence),
        ),
        migrations.AddField(
            model_name='notice',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
