# Generated by Django 2.1.5 on 2019-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190308_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('clg_u_name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('clg_pic', models.ImageField(default='college_list/home_pics/default.jpeg', upload_to='college_list/home_pics/')),
            ],
        ),
    ]
