# Generated by Django 2.1.7 on 2019-04-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190406_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Computer Application', 'Computer Application'), ('Information Technology', 'Information Technology')], max_length=50, null=True, verbose_name='Department')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='main_app.College', verbose_name='College')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='main_app.Department', verbose_name='Department'),
        ),
    ]
