# Generated by Django 2.1.7 on 2019-04-10 14:37

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190410_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=main_app.models.Syllabus.current_year, verbose_name='Session start year')),
                ('syllabus', models.FileField(upload_to=main_app.models.syllabus_path, verbose_name='Syllabus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='main_app.College', verbose_name='College')),
            ],
        ),
        migrations.AlterModelOptions(
            name='collegenotice',
            options={'verbose_name_plural': '6. College Notice Board'},
        ),
        migrations.AlterModelOptions(
            name='collegepictures',
            options={'verbose_name_plural': '5. College Pictures'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '2. Departments'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '4. Unital Notice'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '3. Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=main_app.models.User.current_year, verbose_name='Session start year'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='main_app.Department', verbose_name='Department'),
        ),
    ]
